import config from '../config';
import * as repoReader from './repo-reader';
import * as repoDb from '../db/repositories';
import { createGitProvider } from './git-providers';
import { emitTicketLog } from '../socket';
import { isAllowedProjectRepoId } from '../security/project-repo';
import type { Ticket, CodingResult, DeployResult, Repo } from '../types';

/**
 * Checks if a repo has enough config to create PRs (via new providers or legacy Bitbucket).
 */
function isRepoConfigured(repo: Repo): boolean {
  // New multi-provider: needs token + owner + repo name
  if (repo.provider_token && repo.provider_owner && repo.provider_repo) return true;
  // Legacy Bitbucket: needs workspace + slug
  if (repo.bitbucket_workspace && repo.bitbucket_repo_slug) return true;
  return false;
}

/**
 * Get a GitProvider instance from a Repo record.
 */
function getProvider(repo: Repo) {
  return createGitProvider(
    repo.git_provider || 'bitbucket',
    repo.provider_token || '',
    repo.provider_owner || repo.bitbucket_workspace,
    repo.provider_repo || repo.bitbucket_repo_slug,
  );
}

function resolveAuthorizedRepo(ticket: Ticket): Repo | null {
  if (!ticket.project_id) {
    throw new Error(`Ticket "${ticket.id}" has no project context`);
  }

  const project = repoDb.findProjectById(ticket.project_id);
  if (!project || !project.default_repo) {
    throw new Error(`Project "${ticket.project_id}" has no default repo configured`);
  }

  const projectRepoId = String(project.default_repo).trim();
  if (!isAllowedProjectRepoId(ticket.project_id, projectRepoId)) {
    throw new Error(`Security policy blocked unauthorized repo id for project ${ticket.project_id}`);
  }

  const ticketRepoId = String(ticket.repo || projectRepoId).trim();
  if (ticketRepoId !== projectRepoId) {
    throw new Error(`Security policy blocked repo mismatch for project ${ticket.project_id}`);
  }

  return repoDb.findRepoById(projectRepoId) || null;
}

/**
 * Deploy to staging: commit, push, create PR.
 */
async function deployToStaging(ticket: Ticket, codingResult: CodingResult): Promise<DeployResult> {
  const repo = resolveAuthorizedRepo(ticket);

  if (!repo || !isRepoConfigured(repo)) {
    // Simulation mode — no Git configured
    emitTicketLog(ticket.id, 'Mode simulation: pas de repo Git configuré', 'warning', 'deploying');
    return {
      prUrl: '#simulation',
      prId: 0,
      stagingUrl: config.stagingBaseUrl ? `${config.stagingBaseUrl}/ticket-${ticket.id}` : '',
    };
  }

  const branchName = codingResult.branchName;
  const commitMessage = `[CrabCreate #${ticket.id}] ${ticket.title}\n\n${codingResult.summary}`;

  // Commit and push
  if (codingResult.repoDir) {
    await repoReader.commitAndPush(codingResult.repoDir, branchName, commitMessage);
    emitTicketLog(ticket.id, `Branche "${branchName}" pushée`, 'success', 'deploying');
  }

  // Create PR via provider
  const provider = getProvider(repo);
  const targetBranch = repo.default_branch || repoDb.getConfig('git_default_branch') || 'master';
  const pr = await provider.createPR(
    branchName,
    targetBranch,
    `[CrabCreate #${ticket.id}] ${ticket.title}`,
    `**Auto-generated by CrabCreate**\n\n${ticket.description}\n\n---\nAI Model: ${ticket.ai_model}\nReview Score: ${ticket.ai_review_score || 'N/A'}/100`,
  );

  const stagingUrl = config.stagingBaseUrl ? `${config.stagingBaseUrl}/ticket-${ticket.id}` : pr.url;

  return {
    prUrl: pr.url,
    prId: pr.id,
    stagingUrl,
  };
}

/**
 * Merge PR to production (approve flow).
 */
async function mergeToProduction(ticket: Ticket): Promise<void> {
  const repo = resolveAuthorizedRepo(ticket);

  if (!repo || !isRepoConfigured(repo) || !ticket.pr_id) {
    emitTicketLog(ticket.id, 'Mode simulation: merge simulé', 'info', 'deploying');
    return;
  }

  const mergeStrategy = repoDb.getConfig('git_merge_strategy') || 'merge_commit';
  const provider = getProvider(repo);
  await provider.mergePR(ticket.pr_id, mergeStrategy);
  emitTicketLog(ticket.id, 'PR mergée avec succès', 'success', 'deploying');
}

/**
 * Close/decline PR (reject flow).
 */
async function closePR(ticket: Ticket): Promise<void> {
  const repo = resolveAuthorizedRepo(ticket);

  if (!repo || !isRepoConfigured(repo) || !ticket.pr_id) {
    return;
  }

  const provider = getProvider(repo);
  await provider.declinePR(ticket.pr_id);
  emitTicketLog(ticket.id, 'PR déclinée', 'info', 'deploying');
}

/**
 * Rollback — create a revert commit on master.
 */
async function rollback(ticket: Ticket): Promise<void> {
  emitTicketLog(ticket.id, 'Rollback en cours (simulation)...', 'warning', 'deploying');
  // In a real setup, this would create a revert commit via git or the provider's API
  emitTicketLog(ticket.id, 'Rollback terminé', 'success', 'deploying');
}

export { deployToStaging, mergeToProduction, closePR, rollback };
