import { useLanguage } from '../../hooks/useLanguage';

export default function LegalPage() {
  const { t, lang } = useLanguage();

  return (
    <div className="min-h-screen">
      <div className="max-w-3xl mx-auto px-6 pt-20 pb-24">
        <h1 className="text-3xl font-extrabold text-tx-primary font-display mb-10">{t.legalTitle}</h1>

        <div className="prose prose-sm text-tx-secondary space-y-6 leading-relaxed">
          {lang === 'fr' ? (
            <>
              <section>
                <h2 className="text-lg font-bold text-tx-primary mb-3">1. Mentions Lgales</h2>
                <p>Le site CrabCreate est dit par CrabCreate SAS.</p>
                <p>Adresse : Paris, France</p>
                <p>Contact : contact@crabcreate.com</p>
                <p>Directeur de la publication : CrabCreate SAS</p>
                <p>Hbergeur : OVH SAS, 2 rue Kellermann, 59100 Roubaix, France</p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-tx-primary mb-3">2. Conditions Gnrales d'Utilisation</h2>
                <p>En utilisant CrabCreate, vous acceptez les prsentes conditions. Le service est fourni "en l'tat" sans garantie d'aucune sorte.</p>
                <p>L'utilisateur s'engage  ne pas utiliser le service  des fins illgales ou contraires aux bonnes murs.</p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-tx-primary mb-3">3. Proprit Intellectuelle</h2>
                <p>Le code gnr par l'IA via CrabCreate appartient  l'utilisateur. Les lments graphiques, logos et textes du site restent la proprit de CrabCreate SAS.</p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-tx-primary mb-3">4. Limitation de Responsabilit</h2>
                <p>CrabCreate ne saurait tre tenu responsable des dommages directs ou indirects rsultant de l'utilisation du service, notamment du code gnr par l'IA.</p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-tx-primary mb-3">5. Droit Applicable</h2>
                <p>Les prsentes conditions sont rgies par le droit franais. Tout litige sera soumis aux tribunaux comptents de Paris.</p>
              </section>
            </>
          ) : (
            <>
              <section>
                <h2 className="text-lg font-bold text-tx-primary mb-3">1. Legal Notice</h2>
                <p>CrabCreate is published by CrabCreate SAS.</p>
                <p>Address: Paris, France</p>
                <p>Contact: contact@crabcreate.com</p>
                <p>Publication director: CrabCreate SAS</p>
                <p>Hosting: OVH SAS, 2 rue Kellermann, 59100 Roubaix, France</p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-tx-primary mb-3">2. Terms of Service</h2>
                <p>By using CrabCreate, you agree to these terms. The service is provided "as is" without any warranty.</p>
                <p>Users agree not to use the service for illegal purposes or purposes contrary to public morals.</p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-tx-primary mb-3">3. Intellectual Property</h2>
                <p>Code generated by the AI via CrabCreate belongs to the user. Graphical elements, logos and site texts remain the property of CrabCreate SAS.</p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-tx-primary mb-3">4. Limitation of Liability</h2>
                <p>CrabCreate cannot be held responsible for direct or indirect damages resulting from the use of the service, including AI-generated code.</p>
              </section>

              <section>
                <h2 className="text-lg font-bold text-tx-primary mb-3">5. Applicable Law</h2>
                <p>These terms are governed by French law. Any dispute shall be submitted to the competent courts of Paris.</p>
              </section>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
